version: '3.3'
services:
  onfly:
    build: ./
    container_name: nginx-onfly
    ports:
      - 8000:80
    volumes:
      - ./:/usr/share/nginx/html
    restart: always
    networks:
      - onfly

  db:
    image: mysql
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: onfly
      MYSQL_DATABASE: onfly
      MYSQL_USER: onfly
      MYSQL_PASSWORD: onfly
    volumes:
      - .docker/dbdata:/var/lib/mysql
    networks:
      - onfly

networks:
  onfly:
    driver: bridge